name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini
  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - NOMBRE="Julian"
      - APELLIDO="Fernandez"
      - DOCUMENTO=38943790
      - NACIMIENTO=1993-09-21
      - NUMERO=9179
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/dataset/agency-1.csv:/agency.csv
  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - NOMBRE="Lionel"
      - APELLIDO="Fernandez"
      - DOCUMENTO=33054010
      - NACIMIENTO=2010-12-04
      - NUMERO=6884
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/dataset/agency-2.csv:/agency.csv
  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - NOMBRE="Lionel"
      - APELLIDO="Messi"
      - DOCUMENTO=51350835
      - NACIMIENTO=2007-06-16
      - NUMERO=2975
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/dataset/agency-3.csv:/agency.csv
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
